name: Release

on:
  push:
    tags:
      - 'v*'  # Esegue l'azione su ogni push di un tag che inizia con 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'  # Specifica la versione di Go che vuoi usare

      - name: Install Dependencies
        if: matrix.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libglfw3-dev libx11-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev libxxf86vm-dev

      - name: Build Linux Executable
        if: matrix.os == 'ubuntu-latest'
        run: GOOS=linux GOARCH=${{ matrix.arch }} go build -o myapp-linux-amd64 ./cmd/fractal

      - name: Build Windows Executable
        if: matrix.os == 'windows-latest'
        run: GOOS=windows GOARCH=${{ matrix.arch }} go build -o myapp-windows-amd64.exe ./cmd/fractal


      - name: List generated files
        run: ls -l

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            myapp-linux-amd64
            myapp-windows-amd64.exe
          body: |
            Release of version ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

