name: Release

on:
  push:
    tags:
      - 'v*'  # Esegue l'azione su ogni push di un tag che inizia con 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        os: [linux, windows]
        arch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'  # Specifica la versione di Go che vuoi usare

      - name: Install Dependencies
        if: matrix.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libglfw3-dev libx11-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev libxxf86vm-dev

      - name: Build
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o myapp-${{ matrix.os }}-${{ matrix.arch }} ./cmd/fractal

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref }}
          files: |
            myapp-linux-amd64
            myapp-windows-amd64.exe
            myapp-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

